language: r
# dist: bionic # Uncomment until fix of https://travis-ci.community/t/r-install-broken-travis-ci-rstudio-org-returns-403/9640
cache: packages
os: linux

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - richelbilderbeek/mhcnuggetsr
  - richelbilderbeek/mhcnpreds
  - richelbilderbeek/pureseqtmr
  - richelbilderbeek/epitope-prediction
  - richelbilderbeek/epiprepreds
  - richelbilderbeek/netmhc2pan
  - richelbilderbeek/nmhc2ppreds
  - richelbilderbeek/bbbq

before_script:
  - Rscript -e 'remotes::install_github("richelbilderbeek/pureseqtmr")'
  - Rscript -e 'pureseqtmr::install_pureseqtm()'

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'
  - # No local files created
  - # if [[ $(egrep -R "\"~" --include={*.R,*.Rmd} | egrep -v README.Rmd) ]]; then echo "Local file created"; exit 1; fi;
  - Rscript -e 'pureseqtmr::pureseqtmr_report()'

after_failure:
  - ls
  - Rscript -e 'pureseqtmr::pureseqtmr_report()'

