language: r
cache: packages
os: linux

r_packages:
  - devtools
  - rgl

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - richelbilderbeek/tmhmm
  - richelbilderbeek/mhcnpreds
  - richelbilderbeek/pureseqtmr
  - richelbilderbeek/epitope-prediction
  - richelbilderbeek/epiprepreds
  - richelbilderbeek/netmhc2pan
  - richelbilderbeek/nmhc2ppreds
  - richelbilderbeek/bbbq

bioc_packages:
  - msa
  - bios2mds

before_install:
  # Rmpfr
  - sudo apt install -qq libmpfr-dev
  # ImageMagick
  #- sudo add-apt-repository -y ppa:opencpu/imagemagick
  #- sudo apt-get update
  - sudo apt-get install -y libmagick++-dev
  # Fix rJava error, from https://travis-ci.community/t/cannot-connect-to-java-from-r/9754/8
  #- sudo $(which R) CMD javareconf
  # bios2mds
  - sudo apt-get install libglu1-mesa-dev

before_script:
  - Rscript -e 'remotes::install_github("richelbilderbeek/pureseqtmr")'
  - Rscript -e 'pureseqtmr::install_pureseqtm()'
  - Rscript -e 'remotes::install_github("richelbilderbeek/mhcnuggetsr")'
  - Rscript -e 'mhcnuggetsr::install_mhcnuggets()'

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'
  - # No local files created
  - # if [[ $(egrep -R "\"~" --include={*.R,*.Rmd} | egrep -v README.Rmd) ]]; then echo "Local file created"; exit 1; fi;
  - Rscript -e 'pureseqtmr::pureseqtmr_report()'
  # Download thesis
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

after_failure:
  - ls
  - Rscript -e 'pureseqtmr::pureseqtmr_report()'
  # Download thesis
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

